##################################################################################################
# tcp Notification services
##################################################################################################
apiVersion: "v1"
kind: Service
metadata:
  name: hc-notifications-api-svc
  labels:
    app: notification-business
    service: notification-business-svc
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: notification-business
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-notifications-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-business
      version: v1
  template:
    metadata:
      labels:
        app: notification-business
        version: v1
    spec:
      containers:
      - name: hc-notifications-api-app
        image: hc-tcp-notifications-nest-ms:latest
        env:
        - name: PORT
          value: "3000"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
