apiVersion: apps/v1
kind: Deployment
metadata:
  name: hc-notifications-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-business
      version: v1
  template:
    metadata:
      labels:
        app: notification-business
        version: v1
    spec:
      containers:
      - name: hc-notifications-api-app
        image: input_image
        env:
        - name: PORT
          value: "3000"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000