apiVersion: "v1"
kind: Service
metadata:
  name: hc-notifications-api-svc
  labels:
    app: notification-business
    service: notification-business-svc
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: notification-business